### ISSUE TITLE
Simple_GA: Wrong decay parameter ("sigma_limit" instead of "sigma_decay")

### ISSUE THREAD

**Issue by nlsfnr** [RobertTLange/evosax#3]
It seems that there is a typo in the SimpleGA strategy's "tell_strategy" method ([line](https://github.com/RobertTLange/evosax/blob/63f70fa8207dd3404f0bb2a339fab4ef7d05775d/evosax/strategies/simple_ga.py#L97)):

Instead of updating `state["sigma"]` with `state["sigma"] * state["sigma_decay"]` (correct), it says: `state["sigma"] * state["sigma_limit"]` (wrong).

**Comment by RobertTLange** [comment]
Good catch! Thank you very much. It is fixed in 57235ca15c75ec9804463f31286c1ff96b580708.
