### ISSUE TITLE
OpenES Implementation

### ISSUE THREAD

**Issue by barneyhill** [RobertTLange/evosax#36]
Just looking through this library but couldn't find the OpenES implementation linked in the README - https://github.com/RobertTLange/evosax/blob/main/evosax/strategies/open_es.py. Is this link correct?

Great library btw - many thanks,
Barney

**Comment by RobertTLange** [comment]
Thank you for the kind words and happy new year. The link seems to work for me. Can you double check?

Best wishes,
Rob
