### ISSUE TITLE
Integer Overflow for Large Dimension Problems

### ISSUE THREAD

**Issue by twoletters** [RobertTLange/evosax#40]
`num_dims` is of type `int32` and can overflow when squared:

https://github.com/RobertTLange/evosax/blob/3c7b751c434cf374516c261a8af367d492f5f859/evosax/strategies/cma_es.py#L65

Casting `num_dims` as a `float` fixes the issue:

```
        / (float(num_dims + 2) ** 2 + alpha_cov * mu_eff / 2),
```

**Comment by RobertTLange** [comment]
Hi @twoletters,
Sorry for the super late response and thank you for raising this! you are right. For large network sizes/dimensions this will cause an overflow error. I have somehow fixed this in `Sep_CMA_ES` by fixing the value to a max of 40k in the development branch.

https://github.com/RobertTLange/evosax/blob/2f9ec7935108862e3c45a9413fffbf56c34d5341/evosax/strategies/sep_cma_es.py#L89

It is only used in computing hyperparameters/learning rates in CMA-style algorithms and from some experiments it seems to not hurt. I will add the same clipping to the other CMA variants. 

Let me know if you encounter any other issues. Best wishes and again thank you, Rob
